// Post detail actions
export const GET_POST_FAILURE = 'GET_POST_FAILURE'
export const GET_POST_REQUEST = 'GET_POST_REQUEST'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'

// Subreddit actions
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE'
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'

// Menu actions
export const SUBREDDIT_EXISTENCE_FAILURE = 'SUBREDDIT_EXISTENCE_FAILURE'
export const SUBREDDIT_EXISTENCE_REQUEST = 'SUBREDDIT_EXISTENCE_REQUEST'
export const SUBREDDIT_EXISTENCE_SUCCESS = 'SUBREDDIT_EXISTENCE_SUCCESS'
export const MENU_ITEMS_LOADED = 'MENU_ITEMS_LOADED'
